version: '3.9'

services:

  prod-web:
    container_name: my-awesome-app-bwk-aws
    image: brennanknopf/my-awesome-app-bwk:latest

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:8080'